### PR TITLE
Use `https` lib to issue https requests for browserscope API

### PR DESCRIPTION
**Pull request by steponas**

### CODE REVIEW

**Comment by maxbeatty** [comment]
@steponas will you rebase with our master? #106 should get tests on travis passing ✅

**Comment by steponas** [comment]
@maxbeatty I did rebase all three branches and force-pushed. Not sure if this will trigger a re-test of the branches.

**Comment by steponas** [comment]
Ok, seems closing and reopening should trigger a rebuild. Have done that.

**Comment by mathiasbynens** [comment]
Hmm, just pushing to a branch linked to a PR should trigger a rebuild. For some reason the Travis UI has gone missing from this page, though…

**Comment by steponas** [comment]
Well, probably the issue is that I did a rebase, as suggested. I can't simply push it, as it does rewrite the history. So I had to use the `--force` git flag. Yet that has possibly changed the git refs, so we lost the travis build link.

Maybe someone with write access in travis can press the "refresh" button and see if that helps? Thanks.

**Comment by mathiasbynens** [comment]
@steponas Nah, force-pushing doesn’t usually affect Travis for PRs. Something else is going on…

I just hit refresh on https://travis-ci.org/jsperf/jsperf.com/builds/128814719.

**Comment by mathiasbynens** [comment]
I just hit refresh on https://travis-ci.org/jsperf/jsperf.com/builds/128814719 (which I think is tied to that specific commit rather than this PR):

> An error occured when restarting the build

**Comment by steponas** [comment]
If it was tied to the previous commit, then it's very possible that it got broken due to rebasing. As the commit hashes should have changed.

**Comment by steponas** [comment]
Yeah, following the "commit" link in Travis leads to nowhere.
Anyone minds me doing a empty-commit and pushing it? I think travis should build fine then.

**Comment by maxbeatty** [comment]
Fixed via https://github.com/jsperf/jsperf.com/commit/50bf885a3deead4dfb55f44c953d59619309d441

Thanks again @steponas

**Comment by mathiasbynens** [comment]
Thanks, @steponas!

**Pull request closed without merging**
