### PR TITLE
Make it easier to contribute

### PR DESCRIPTION
**Pull request by maxbeatty**
We've been seeing more contributions from the community which is great! However, it was noticably difficult due to Docker, OAuth, and other pieces that weren't core to the real functionality of jsperf. This PR aims to address a lot of the hurdles to local development.

- [x] no more Docker (run node directly)
- [x] no more Docker Compose (bring your own mysql)
- [x] no more end to end tests (that were never being run)
- [x] no more (faulty) setup scripts (define everything in `.env` yourself)
- [x] explicit oauth callback (no more guessing based on scheme, domain, port, etc.)
- [x] replace `debug` with general logger
- [x] log to cloud service in addition to console
- [x] turn off Docker Hub webhooks
- [x] database schema migration (that automatically applies)

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Reduced complexity is a huge win. Great stuff, @maxbeatty! 👍

**Comment by madskonradsen** [comment]
Is the docker-setup being migrated to another repo then? I guess it's still needed for deployment :)

**Comment by asilluron** [comment]
Nicely done @maxbeatty, just killed the dockerhub hooks

**Comment by maxbeatty** [comment]
> Is the docker-setup being migrated to another repo then? I guess it's still needed for deployment

We are moving to [now](https://zeit.co/now) thanks to the good people at Zeit

**Comment by mathiasbynens** [comment]
@maxbeatty I’ll let you do the honors :)

**Comment by Daniel15** [comment]
Out of curiosity - How did Docker make it difficult to contribute? Shouldn't it have made it easier, by assisting with having a consistent environment?

**Comment by maxbeatty** [comment]
A few things I noticed:

- not wanting to learn or use Docker (database host being hardcoded for Docker required local workarounds folks in this camp)
- challenges getting Docker working (there were a lot of moving pieces, underlying dependencies changed over time, spent more time supporting Docker than getting jsPerf built)
- development workflow preference ("edit file, refresh browser, see changes" not supported because that's not how we ran Docker in "production")
- OAuth callback URLs were a pain because of how ports were appended or not depending on situations or if you were using a VM for Docker

**Pull request merged**
