### PR TITLE
Updated benchmark.js dependency

### PR DESCRIPTION
**Pull request by madskonradsen**

### CODE REVIEW

**Comment by madskonradsen** [comment]
Failing because of outdated Handlebars version which is being updated by the greenkeeper in #154

**Comment by maxbeatty** [comment]
snyk checks aren't required so not worried about it even tho it gives a red x

will you also [update `npm-shrinkwrap`](https://github.com/jsperf/jsperf.com#adding-new-dependencies)?

**Comment by madskonradsen** [comment]
Oh, my bad! Coming up!

**Comment by mathiasbynens** [comment]
https://github.com/jsperf/jsperf.com#adding-new-dependencies might be useful :)

**Comment by madskonradsen** [comment]
Hmmm... Wondering why the diff of shrinkwrap includes changes that have already been merged...

**Comment by maxbeatty** [comment]
sorry to be a nag but can you do a clean shrinkwrap (see end of dependency section in readme) so that only benchmark is changed?

**Comment by madskonradsen** [comment]
Created a new branch, it was easier ;) #156

**Pull request closed without merging**
