### PR TITLE
update readme with some additional information / formatting

### PR DESCRIPTION
**Pull request by swang**
* Use 4 spaces in Markdown to signify a sublist
* Added extra instructions if you run into an `npm install` error
  involving python or if you are upgrading an older version of mysql and
  get an error complaining about the Column count

### CODE REVIEW

**Comment by maxbeatty** [comment]
These are good debugging tips. I'm not sure the README is the best place for them (just to avoid any confusion). Maybe we can put them in a wiki?

**Comment by swang** [comment]
Is there a jsperf wiki at the moment? I think sticking it in a wiki would be okay if it's actually used often otherwise it's not useful to anyone. The reason I stuck it the README is it makes it easier for developers to continue trying to setup a local development environment rather than have them stall during the process. Better to have it up front then having it being hidden somewhere and saves the developer a couple of trips to Google or Stackoverflow to find the issue.

**Comment by maxbeatty** [comment]
I created a wiki and page for [Local Development Debugging](https://github.com/jsperf/jsperf.com/wiki/Local-Development-Debugging) with the content from this PR. Want to add a link to it at the bottom of [this section of the README](https://github.com/jsperf/jsperf.com/blob/f144e66364f02edcac613d77d9bc63274a7b6e44/README.md#how-to-run-a-local-copy-of-jsperf)?

**Comment by swang** [comment]
Do you mean rewrite this PR to just add the link to the wiki? And what about changes to the markdown formatting? Right now in the README there's one line that just says, "install"

**Pull request closed without merging**
