### PR TITLE
Fix tests not being saved when editing an existing page.

### LINKED ISSUE #236: Some tests are not getting posted properly
The `<table>` on https://jsperf.com/cash-vs-jquery-parents/2 has an empty `<tbody>`.

Somehow, no tests were inserted into the database for this page:

```
mysql> select * from tests where pageID = 1303938;
Empty set (0.00 sec)
```

Any ideas how this happened?

### PR DESCRIPTION
**Pull request by konstantinblaesi**
Fixes #236

Looks like ownership verification is broken. If _Name_ aka _author_ is set your are the owner???

### CODE REVIEW

**Comment by elxa** [comment]
Hi @maxbeatty ,

can you merge this?

**Comment by maxbeatty** [comment]
@mathiasbynens will you refresh me when a test should be updated?

**Comment by elxa** [comment]
@maxbeatty Is there anything missing stopping this from being merged?

**Comment by maxbeatty** [comment]
@elxa please be patient. I am waiting on Mathias to clarify when a test should be updated. That response will clarify whether this is a change we should make. I will submit a review when I have all of information I need. Thank you for your contribution, but please be patient.

**Comment by mathiasbynens** [comment]
> when [should] a test be updated?

When the test’s owner edits the test while still logged in to the same session (cookie-wise). On the old jsPerf, that used to be an 8-hour window, but that’s an implementation detail.

**Pull request closed without merging**
