### PR TITLE
Correctly render the slug when it is set

### PR DESCRIPTION
**Pull request by steponas**
This should fix one problem of many in #88

### CODE REVIEW

**Comment by mathiasbynens** [comment]
@maxbeatty The CI build seems to hang on `node setup` which seems unrelated to this change. Any idea what’s going on?

**Comment by steponas** [comment]
@mathiasbynens @maxbeatty if you would compare this (and other two failed) PRs with a working on (like https://travis-ci.org/jsperf/jsperf.com/builds/123997899) it's clear that `Setting environment variables from repository settings` is missing quite some env variables. That's why the "setup" part is waiting for user input on Browserscope API key, and that times out after 10m.

I'd say it's a travis configuration issue.

**Comment by maxbeatty** [comment]
The environment variables need to be factored out of the unit tests. It causes problems any time someone submits a PR. I created #105 to track this

**Comment by maxbeatty** [comment]
@steponas will you rebase with our master? #106 should get tests on travis passing ✅

**Comment by maxbeatty** [comment]
@steponas thanks for bearing with us as we got travis straightened out. #107 was able to submit a fork PR successfully

**Pull request closed without merging**
