### PR TITLE
Ensure that edited test cases can be set as synchronous/asynchronous.

### LINKED ISSUE #412: checking the "check if this is an asynchronous test" checkbox has no effect
I get `deferred is not defined` errors. Test case: https://jsperf.com/pouchdb-put-resolve-on-change

### PR DESCRIPTION
**Pull request by bnjmnt4n**
Closes #412.

Not too sure if I should edit any of the tests, please let me know if you want me to do so :)

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Thanks a lot, @bnjmnt4n! Deploying now.

**Comment by mathiasbynens** [comment]
@maxbeatty I’m having issues deploying with `now`. Is everything working for you?

```
> Deploying ~/projects/jsperf.com under mathias
> Using Node.js 8.9.1 (requested: `8.x.x`)
> Ready! https://jsperfcom-dumuiyqstt.now.sh (copied to clipboard) [9s]
> Synced 1 file (334.75KB) [0ms]
> Initializing…
> Initializing…
> Building
> ▲ npm install
> ✓ Using "package-lock.json"
> ⧗ Installing 30 main dependencies…
> ✓ Installed 1226 modules [10s]
> ▲ npm start
> > jsperf.com@2.0.0 start /home/nowuser/src
> > node server.js
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> More details: https://err.sh/now-cli/no-open-port-found
```

**Comment by maxbeatty** [comment]
starts up for me locally. can you double-check that `@jsperf-loggly-token` secret is set properly? there aren't any logs and that's where this startup issue should explain itself (could also just enable good-console always)

**Comment by mathiasbynens** [comment]
Nothing has changed about the `now`/ZEIT setup:

```
$ now secrets ls | grep jsperf-loggly-token
  jsperf-loggly-token      323d ago
```

😕

**Pull request merged**
