### PR TITLE
Remove timeout for loading jsapi

### PR DESCRIPTION
**Pull request by danez**
As discussed in #364

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Note that `public/_js/test.js` is autogenerated/overwritten after running `npm run build`. Could you update `gulpfile.js` as described [here](https://github.com/jsperf/jsperf.com/pull/364#issuecomment-289767249) please? 

Then, once https://github.com/bestiejs/benchmark.js/pull/188 is merged, this PR can be merged too, and this change can be deployed. 👍

**Comment by danez** [comment]
Yes sorry, I slowly start to understand how jsperf is build :)
I changed the PR.

**Comment by mathiasbynens** [comment]
Thank you so much for looking into this and fixing this long-standing issue 👍 You’re a hero!

**Comment by mathiasbynens** [comment]
Okay, so here’s what needs to happen before this can be merged:

1. https://github.com/bestiejs/benchmark.js/pull/188 is merged
2. Benchmark.js tags a new release that contains the abovementioned changes
3. Our `package.json` updates the `devDependency` to point to this new release. See https://github.com/jsperf/jsperf.com/blob/master/CONTRIBUTING.md#adding-new-dependencies

Would you be up for tackling item 3 (as part of this PR) when the time comes?

**Comment by danez** [comment]
Of course.

**Comment by danez** [comment]
Ok I updated benchmark and regenerated the shrinkwrap by doing:
```
rm -rf node_modules/ npm-shrinkwrap.json
npm i
npm shrinkwrap
```

**Comment by mathiasbynens** [comment]
One last thing before we merge this: could you run `npm run build` and commit the changes?

**Comment by danez** [comment]
Done

**Pull request merged**
